<?php
/**
 * API Backend for Arduino Bioresonance Controller
 * 
 * Handles TCP communication with Arduino Nano, session management,
 * and provides a JSON API for the WebUI frontend.
 * 
 * @version 2.0 (Security & Stability Hardened)
 * @author Generated by AI
 */

// --- KONFIGURACJA ---
define('DEBUG_MODE', true);
define('LOG_FILE', __DIR__ . '/debug.log');
define('LOCK_FILE', __DIR__ . '/session.lock');
define('LOCK_TIMEOUT', 30); // Sekundy po których lock jest uznawany za osierocony
define('MAX_LOG_SIZE', 1048576); // 1MB limit dla pliku logów
define('DEFAULT_ARDUINO_IP', '192.168.4.1');
define('DEFAULT_ARDUINO_PORT', 23);

// Inicjalizacja sesji PHP
if (session_status() === PHP_SESSION_NONE) {
    session_start();
}

// Nagłówki bezpieczeństwa i JSON
header('Content-Type: application/json; charset=utf-8');
header('X-Content-Type-Options: nosniff');
header('X-Frame-Options: DENY');

// --- FUNKCJE POMOCNICZE ---

/**
 * Rejestruje funkcję sprzątającą na wypadek nagłego zakończenia skryptu
 */
function register_socket_cleanup(&$socket) {
    register_shutdown_function(function() use (&$socket) {
        if (is_resource($socket) || ($socket instanceof \Socket)) {
            debug_log("SHUTDOWN: Forced socket close due to script termination.");
            @socket_close($socket);
        }
    });
}

/**
 * Bezpieczna funkcja logowania z rotacją pliku
 */
function debug_log($message, $level = 'INFO') {
    if (!DEBUG_MODE) return;

    // Rotacja logu jeśli za duży
    if (file_exists(LOG_FILE) && filesize(LOG_FILE) > MAX_LOG_SIZE) {
        $oldContent = file_get_contents(LOG_FILE);
        // Zachowaj tylko ostatnią połowę pliku
        $lines = explode("\n", $oldContent);
        $lines = array_slice($lines, count($lines) / 2);
        file_put_contents(LOG_FILE, implode("\n", $lines));
    }

    $timestamp = date('Y-m-d H:i:s');
    $logLine = "[$timestamp] [$level] $message\n";
    file_put_contents(LOG_FILE, $logLine, FILE_APPEND | LOCK_EX);
}

/**
 * Zwraca odpowiedź JSON i kończy skrypt
 */
function json_response($success, $data = null, $error = null) {
    echo json_encode([
        'success' => $success,
        'data' => $data,
        'error' => $error,
        'timestamp' => time()
    ]);
    exit;
}

/**
 * Walidacja adresu IP
 */
function validate_ip($ip) {
    return filter_var($ip, FILTER_VALIDATE_IP) !== false;
}

/**
 * Walidacja portu
 */
function validate_port($port) {
    $p = intval($port);
    return ($p > 0 && $p < 65536);
}

/**
 * Escapowanie znaków specjalnych do safe command
 */
function sanitize_command($cmd) {
    // Usuń znaki nowej linii, aby zapobiec injekcjom wieloliniowym
    return preg_replace('/[\r\n]+/', '', trim($cmd));
}

// --- OBSŁUGA BLOKAD (LOCKING) ---

/**
 * Acquires a session lock with stale-lock detection
 */
function acquire_lock() {
    // Sprawdź czy nie ma osieroconego locka
    if (file_exists(LOCK_FILE)) {
        $fileTime = filemtime(LOCK_FILE);
        if ((time() - $fileTime) > LOCK_TIMEOUT) {
            debug_log("LOCK: Removing stale lock file (older than " . LOCK_TIMEOUT . "s)", "WARN");
            @unlink(LOCK_FILE);
        }
    }

    $fp = fopen(LOCK_FILE, 'w+');
    if (!$fp) {
        return false;
    }

    if (!flock($fp, LOCK_EX | LOCK_NB)) {
        fclose($fp);
        return false;
    }
    
    // Zapisz PID procesu w locku dla debugowania
    ftruncate($fp, 0);
    fwrite($fp, json_encode(['pid' => getmypid(), 'time' => time()]));
    fflush($fp);
    
    return $fp;
}

function release_lock($fp) {
    if ($fp) {
        flock($fp, LOCK_UN);
        fclose($fp);
    }
}

// --- KOMUNIKACJA TCP Z ARDUINO ---

/**
 * Łączy się z Arduino, wysyła komendę i odbiera odpowiedź
 * 
 * @param string $command Komenda do wysłania
 * @param string $ip Adres IP Arduino
 * @param int $port Port TCP
 * @return array Wynik operacji
 */
function send_to_arduino($command, $ip, $port) {
    $socket = null;
    $timeout_sec = 2;
    $timeout_usec = 500000;

    debug_log("TCP: Connecting to $ip:$port");

    // 1. Tworzenie socketu
    $socket = socket_create(AF_INET, SOCK_STREAM, SOL_TCP);
    if ($socket === false) {
        $err = socket_last_error();
        $msg = socket_strerror($err);
        debug_log("TCP: Create failed - $msg ($err)", "ERROR");
        return ['success' => false, 'error' => "Socket create failed: $msg"];
    }

    // Rejestracja sprzątania
    register_socket_cleanup($socket);

    // 2. Ustawienie timeoutów
    if (!socket_set_option($socket, SOL_SOCKET, SO_RCVTIMEO, ['sec' => $timeout_sec, 'usec' => $timeout_usec])) {
        debug_log("TCP: Failed to set receive timeout", "WARN");
    }
    if (!socket_set_option($socket, SOL_SOCKET, SO_SNDTIMEO, ['sec' => $timeout_sec, 'usec' => $timeout_usec])) {
        debug_log("TCP: Failed to set send timeout", "WARN");
    }

    // 3. Łączenie
    $result = @socket_connect($socket, $ip, $port);
    if ($result === false) {
        $err = socket_last_error($socket);
        $msg = socket_strerror($err);
        debug_log("TCP: Connect failed - $msg ($err)", "ERROR");
        socket_close($socket);
        return ['success' => false, 'error' => "Connection failed: $msg (Check IP/Port/Arduino)"];
    }

    debug_log("TCP: Connected successfully");

    // 4. Wysyłanie danych
    // Dodajemy newline na koniec komendy jeśli go nie ma (protokół tekstowy)
    if (substr($command, -1) !== "\n") {
        $command .= "\n";
    }
    
    $bytesSent = socket_write($socket, $command, strlen($command));
    if ($bytesSent === false) {
        $err = socket_last_error($socket);
        $msg = socket_strerror($err);
        debug_log("TCP: Write failed - $msg", "ERROR");
        socket_close($socket);
        return ['success' => false, 'error' => "Send failed: $msg"];
    }
    debug_log("TCP: Sent $bytesSent bytes: " . trim($command));

    // 5. Odbieranie odpowiedzi
    $response = "";
    while ($out = socket_read($socket, 2048)) {
        if ($out === false) {
            // Check if it's just a timeout (no data) or real error
            $err = socket_last_error($socket);
            if ($err != SOCKET_ETIMEDOUT && $err != SOCKET_EAGAIN) {
                 debug_log("TCP: Read error - " . socket_strerror($err), "ERROR");
            }
            break; 
        }
        $response .= $out;
        // Jeśli odpowiedź jest kompletna (np. kończy się newline), można przerwać wcześniej
        if (strpos($out, "\n") !== false) break;
    }

    debug_log("TCP: Received: " . trim($response));

    // 6. Zamykanie
    socket_close($socket);
    debug_log("TCP: Connection closed");

    return [
        'success' => true,
        'data' => trim($response),
        'raw_response' => $response
    ];
}

// --- GŁÓWNA LOGIKA API ---

$action = $_POST['action'] ?? $_GET['action'] ?? '';
$ip = $_POST['ip'] ?? $_SESSION['arduino_ip'] ?? DEFAULT_ARDUINO_IP;
$port = $_POST['port'] ?? $_SESSION['arduino_port'] ?? DEFAULT_ARDUINO_PORT;

// Zapisz preferencje w sesji
$_SESSION['arduino_ip'] = $ip;
$_SESSION['arduino_port'] = $port;

debug_log("API Request: action=$action, ip=$ip, port=$port");

switch ($action) {
    case 'connect_test':
        if (!validate_ip($ip)) {
            json_response(false, null, "Invalid IP address format");
        }
        if (!validate_port($port)) {
            json_response(false, null, "Invalid port number");
        }
        
        $result = send_to_arduino("STATUS\n", $ip, $port);
        if ($result['success']) {
            json_response(true, ['message' => 'Connected', 'response' => $result['data']]);
        } else {
            json_response(false, null, $result['error']);
        }
        break;

    case 'get_status':
        $fp = acquire_lock();
        if (!$fp) {
            json_response(false, null, "System busy (another operation in progress)");
        }
        
        try {
            $result = send_to_arduino("STATUS\n", $ip, $port);
            if ($result['success']) {
                // Parsowanie odpowiedzi (przykład: TEMP:30|MEM:50|UP:100)
                $parsed = [];
                $parts = explode('|', $result['data']);
                foreach($parts as $part) {
                    $kv = explode(':', $part);
                    if(count($kv) == 2) $parsed[trim($kv[0])] = trim($kv[1]);
                }
                json_response(true, $parsed);
            } else {
                json_response(false, null, $result['error']);
            }
        } finally {
            release_lock($fp);
        }
        break;

    case 'save_config':
        // Oczekujemy tablicy kanałów w POST
        $channels = $_POST['channels'] ?? [];
        $mode = $_POST['mode'] ?? 'SINGLE';
        
        if (!is_array($channels) || empty($channels)) {
            json_response(false, null, "No channel data provided");
        }

        $fp = acquire_lock();
        if (!$fp) {
            json_response(false, null, "System busy");
        }

        try {
            // Budowanie komendy konfiguracyjnej
            $configString = "CONFIG MODE:$mode\n";
            
            foreach ($channels as $ch) {
                // Walidacja i sanityzacja danych kanału
                $id = intval($ch['id']);
                $name = substr(trim($ch['name']), 0, 20); // Max 20 znaków
                $type = intval($ch['type']);
                $freq = floatval($ch['freq']);
                $duty = intval($ch['duty']);
                $intens = intval($ch['intensity']);
                $mod = intval($ch['modulation']);
                $en = ($ch['enabled'] ? 1 : 0);

                // Zakresy (Safety checks)
                if ($freq < 0) $freq = 0;
                if ($duty < 0 || $duty > 100) $duty = 50;
                if ($intens < 0 || $intens > 255) $intens = 0;

                $configString .= "CH:$id|$name|$type|$freq|$duty|$intens|$mod|$en\n";
            }
            
            $configString .= "END_CONFIG\n";

            debug_log("Sending bulk config...");
            $result = send_to_arduino($configString, $ip, $port);
            
            if ($result['success']) {
                json_response(true, ['message' => 'Configuration saved', 'details' => $result['data']]);
            } else {
                json_response(false, null, "Failed to save config: " . $result['error']);
            }

        } finally {
            release_lock($fp);
        }
        break;

    case 'control':
        $subAction = $_POST['sub'] ?? ''; // START, STOP, PAUSE
        
        if (!in_array($subAction, ['START', 'STOP', 'PAUSE'])) {
            json_response(false, null, "Invalid control command");
        }

        $fp = acquire_lock();
        if (!$fp) {
            json_response(false, null, "System busy");
        }

        try {
            $cmd = $subAction . "\n";
            $result = send_to_arduino($cmd, $ip, $port);
            
            if ($result['success']) {
                json_response(true, ['message' => "$subAction command sent", 'response' => $result['data']]);
            } else {
                json_response(false, null, $result['error']);
            }
        } finally {
            release_lock($fp);
        }
        break;

    case 'raw_command':
        $cmd = $_POST['command'] ?? '';
        if (empty($cmd)) {
            json_response(false, null, "Empty command");
        }

        // Sanityzacja komendy
        $safeCmd = sanitize_command($cmd);
        
        // Lista zabronionych komend (opcjonalne zabezpieczenie)
        $forbidden = ['FORMAT', 'RESET_FACTORY']; 
        foreach($forbidden as $bad) {
            if (strpos(strtoupper($safeCmd), $bad) !== false) {
                json_response(false, null, "Command blocked for safety: $bad");
            }
        }

        $fp = acquire_lock();
        if (!$fp) {
            json_response(false, null, "System busy");
        }

        try {
            $result = send_to_arduino($safeCmd . "\n", $ip, $port);
            if ($result['success']) {
                json_response(true, ['response' => $result['data']]);
            } else {
                json_response(false, null, $result['error']);
            }
        } finally {
            release_lock($fp);
        }
        break;

    default:
        json_response(false, null, "Unknown action: $action");
        break;
}
?>
